branches:
  only:
    - master

language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - node ./node_modules/ugly-build/index.js build
  
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    local_dir: .build
